Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,11 +2,11 @@ name: CI
 
 on:
   push:
-    branches: 
+    branches:
       - "main"
       - "develop"
   pull_request:
-    branches: 
+    branches:
       - "main"
       - "develop"
   workflow_dispatch:
@@ -42,3 +42,16 @@ jobs:
           token: ${{ secrets.COVERAGE_ROBOT_TOKEN }}
           endpoint: https://api.coveragerobot.com/v1
           github-token: ${{ github.token }}
+
+      - name: Clean up existing files
+        run: |
+          echo "Cleaning up existing files..."
+          rm -rf ../../../go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/*
+
+      - name: Handle tar errors
+        run: |
+          tar -xvf your_tar_file.tar.gz || {
+            echo "Tar extraction failed, retrying..."
+            rm -rf ../../../go/pkg/mod/github.com/davecgh/go-spew@v1.1.1/*
+            tar -xvf your_tar_file.tar.gz
+          }
